title:        Paulo Suzart
tagline:      'my blog at github.io'
description:  'I am working with Java platform for the last 10 years. Former SOA architect, now my priority is functional programming (mostly with clojure), virtualization and cloud computing.'
url:          http://paulosuzart.github.io
version:      1.1.1
author:
  name:       'Paulo Suzart'
  email:      'paulosuzart@gmail.com'
markdown:     rdiscount
permalink:    /blog/:year/:month/:day/:title/
pygments:     true
paginate:     5
tracking_id : 'UA-26676810-1'
disqus_short_name: paulosuzartblog      