title:        Paulo Suzart
tagline:      'my blog at github.io'
description:  'Functional programming (mostly with clojure), virtualization and cloud computing.'
url:          http://paulosuzart.github.io
version:      1.1.1
author:
  name:       'Paulo Suzart'
  email:      'paulosuzart@gmail.com'
markdown:     rdiscount
permalink:    /blog/:year/:month/:day/:title/
highlighter:  pygments
paginate:     5
tracking_id : 'UA-26676810-1'
disqus_short_name: paulosuzartblog
layouts: ./_layouts
