title:        Paulo Suzart
tagline:      'my blog at github.io'
description:  'Functional programming and a bit of a lot.'
version:      1.1.1
baseUrl: https://paulosuzart.github.io
owner:
  name:       'Paulo Suzart'
  job:        'FP and more'
  github:     'github.com/paulosuzart'
  bio:        'software engineer | functional programming fan'
  linkedin:   'https://www.linkedin.com/in/paulosuzart/'
  disqus-shortname: paulosuzartblog
  disqus_short_name: paulosuzartblog
  google:
    analytics: 'UA-26676810-1'
markdown: kramdown
permalink:    /blog/:year/:month/:day/:title/
highlighter:  rouge
# paginate: 8
# paginate_path: '/blog/pages/page:num/'
tracking_id : 'UA-26676810-1'
disqus_short_name: paulosuzartblog
gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed

excerpt_separator: <!--more-->
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true
  sort_field: 'date'
  sort_reverse: true
  permalink: '/blog/page:num/'